spring.config.import=optional:file:.env[.properties]
spring.application.name=imovcg-back

spring.datasource.url=jdbc:mysql://localhost:3306/imovcg?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${CONFIRMATION_EMAIL_ADDRESS}
spring.mail.password=${CONFIRMATION_EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.confirmation-base-url=http://localhost:8080